### ISSUE TITLE
Postbuild copyfiles fail

### ISSUE THREAD

**Issue by HenryDev** [karl-run/spring-boot-kotlin-cra#1]
When I run the [postbuild](https://github.com/karl-run/spring-boot-kotlin-cra/blob/d23478b64e61acb38273772d18e789b858c8bfa9/web/package.json#L17) job it fails:

```
> web@0.1.0 postbuild /Users/h/IdeaProjects/spring-boot-kotlin-cra/web
> rimraf ../server/src/main/resources/static && copyfiles -E -u 1 build/**/* ../server/src/main/resources/static

Error: nothing coppied
    at DestroyableTransform.<anonymous> (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/copyfiles/index.js:161:23)
    at DestroyableTransform.emit (events.js:202:15)
    at finishMaybe (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/readable-stream/lib/_stream_writable.js:630:14)
    at endWritable (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at DestroyableTransform.onend (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:285:13)
    at DestroyableTransform.emit (events.js:202:15)
    at endReadableNT (/Users/h/IdeaProjects/spring-boot-kotlin-cra/web/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@0.1.0 postbuild: `rimraf ../server/src/main/resources/static && copyfiles -E -u 1 build/**/* ../server/src/main/resources/static`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web@0.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/h/.npm/_logs/2019-03-08T22_56_41_421Z-debug.log

```

**Comment by karl-run** [comment]
I've had some issues with this. I looked into it and it seems to relate to the globbing (`build/**/*`) and copyfiles had a note in their README about wrapping the globstars in case your terminal doesn't support them. :man_shrugging: 

01e4a6c5ac8e879b5bf49ede544a059574c301fa fixes this for me an Linux. If it doesn't work for you just reopen this issue.
